# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gyro_pb2 as gyro__pb2


class GyroStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGyro = channel.unary_unary(
                '/gyro.Gyro/GetGyro',
                request_serializer=gyro__pb2.GyroRequest.SerializeToString,
                response_deserializer=gyro__pb2.GyroReply.FromString,
                )


class GyroServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGyro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GyroServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGyro': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGyro,
                    request_deserializer=gyro__pb2.GyroRequest.FromString,
                    response_serializer=gyro__pb2.GyroReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gyro.Gyro', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Gyro(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGyro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gyro.Gyro/GetGyro',
            gyro__pb2.GyroRequest.SerializeToString,
            gyro__pb2.GyroReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
