# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gyro.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngyro.proto\x12\x04gyro\"\r\n\x0bGyroRequest\",\n\tGyroReply\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x32\x35\n\x04Gyro\x12-\n\x07GetGyro\x12\x11.gyro.GyroRequest\x1a\x0f.gyro.GyroReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gyro_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GYROREQUEST._serialized_start=20
  _GYROREQUEST._serialized_end=33
  _GYROREPLY._serialized_start=35
  _GYROREPLY._serialized_end=79
  _GYRO._serialized_start=81
  _GYRO._serialized_end=134
# @@protoc_insertion_point(module_scope)
